# Generated by Django 5.2.4 on 2025-07-31 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ssm_number', models.CharField(max_length=50)),
                ('incorporation_date', models.DateField()),
                ('business_address', models.TextField()),
                ('nature_of_business', models.CharField(max_length=255)),
                ('financial_year_end', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('ic_number', models.CharField(max_length=20)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('residential_address', models.TextField()),
                ('appointment_date', models.DateField()),
                ('resignation_date', models.DateField(blank=True, null=True)),
                ('is_shareholder', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directors', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='Shareholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('ic_number', models.CharField(max_length=20)),
                ('residential_address', models.TextField()),
                ('shareholding', models.PositiveIntegerField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_acquired', models.DateField()),
                ('date_transferred_in', models.DateField(blank=True, null=True)),
                ('date_transferred_out', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shareholders', to='companies.company')),
            ],
        ),
    ]
