# Generated by Django 5.2.4 on 2025-07-31 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='nature_of_business',
        ),
        migrations.AddField(
            model_name='company',
            name='nature_of_business_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='nature_of_business_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='nature_of_business_3',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
