# Generated by Django 5.2.4 on 2025-07-31 22:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_remove_company_nature_of_business_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='business_address',
        ),
        migrations.AddField(
            model_name='company',
            name='business_address_line1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='business_address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='business_address_line3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='business_postcode',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator(message='Postcode must be exactly 5 digits.', regex='^\\d{5}$')]),
        ),
        migrations.AddField(
            model_name='company',
            name='business_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='business_town',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='incorporation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
