# Generated by Django 5.2.4 on 2025-08-01 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_remove_company_business_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='nature_of_business_1',
            field=models.CharField(max_length=255),
        ),
    ]
