# Generated by Django 5.2.4 on 2025-08-01 01:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_nature_of_business_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='ic_number',
        ),
        migrations.RemoveField(
            model_name='director',
            name='residential_address',
        ),
        migrations.RemoveField(
            model_name='shareholder',
            name='date_transferred_in',
        ),
        migrations.RemoveField(
            model_name='shareholder',
            name='date_transferred_out',
        ),
        migrations.RemoveField(
            model_name='shareholder',
            name='ic_number',
        ),
        migrations.RemoveField(
            model_name='shareholder',
            name='residential_address',
        ),
        migrations.AddField(
            model_name='director',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='director',
            name='address_line3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='director',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='director',
            name='ic_passport',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='director',
            name='postcode',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator(message='Postcode must be exactly 5 digits.', regex='^\\d{5}$')]),
        ),
        migrations.AddField(
            model_name='director',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='town',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shareholder',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shareholder',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='shareholder',
            name='address_line3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='shareholder',
            name='ic_passport',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shareholder',
            name='postcode',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator(message='Postcode must be exactly 5 digits.', regex='^\\d{5}$')]),
        ),
        migrations.AddField(
            model_name='shareholder',
            name='shareholder_type',
            field=models.CharField(choices=[('ordinary', 'Ordinary Shareholder'), ('preference', 'Preference Shareholder'), ('other', 'Other')], default='ordinary', max_length=50),
        ),
        migrations.AddField(
            model_name='shareholder',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shareholder',
            name='town',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AlterField(
            model_name='shareholder',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AlterField(
            model_name='shareholder',
            name='percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
