# Generated by Django 5.2.4 on 2025-08-01 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_remove_director_ic_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='financial_year_end',
        ),
        migrations.RemoveField(
            model_name='company',
            name='name',
        ),
        migrations.RemoveField(
            model_name='director',
            name='position',
        ),
        migrations.RemoveField(
            model_name='shareholder',
            name='date_acquired',
        ),
        migrations.RemoveField(
            model_name='shareholder',
            name='percentage',
        ),
        migrations.AddField(
            model_name='company',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='registered_branch',
            field=models.CharField(blank=True, choices=[('HQ', 'HQ'), ('CHERAS', 'Cheras'), ('SHAH ALAM', 'Shah Alam'), ('SKUDAI', 'Skudai'), ('KUANTAN', 'Kuantan')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shareholder',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='shareholder',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('position', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
        ),
    ]
