# Generated by Django 5.2.4 on 2025-08-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_remove_company_financial_year_end_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='business_address_line2',
            new_name='address_line2',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='business_address_line3',
            new_name='address_line3',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='business_postcode',
            new_name='postcode',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='business_state',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='business_town',
            new_name='town',
        ),
        migrations.RemoveField(
            model_name='company',
            name='business_address_line1',
        ),
        migrations.AddField(
            model_name='company',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='registered_branch',
            field=models.CharField(blank=True, choices=[('HQ', 'HQ'), ('CHERAS', 'Cheras'), ('SHAH ALAM', 'Shah Alam'), ('SKUDAI', 'Skudai'), ('KUANTAN', 'Kuantan')], default='HQ', max_length=50, null=True),
        ),
    ]
