# Generated by Django 5.2.4 on 2025-08-01 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_rename_business_address_line2_company_address_line2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='registered_branch',
            new_name='amr_cosec_branch',
        ),
    ]
