# Generated by Django 5.2.4 on 2025-08-01 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_rename_registered_branch_company_amr_cosec_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auditor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('auditor_license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('auditor_address', models.TextField(blank=True, null=True)),
                ('tax_agent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('tax_agent_ssm_number', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_agent_address', models.TextField(blank=True, null=True)),
                ('financial_year_end', models.CharField(blank=True, help_text='Format: e.g. 31 December or 30 September', max_length=20, null=True)),
                ('latest_annual_return_filed', models.DateField(blank=True, null=True)),
                ('latest_financial_statement_filed', models.DateField(blank=True, null=True)),
                ('beneficial_owner_declaration', models.CharField(choices=[('Declared', 'Declared'), ('Pending', 'Pending')], default='Pending', max_length=10)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_info', to='companies.company')),
            ],
        ),
    ]
