# Generated by Django 5.2.4 on 2025-08-02 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_complianceinformation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactperson',
            old_name='email',
            new_name='email_address',
        ),
    ]
