# Generated by Django 5.2.4 on 2025-08-02 14:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_rename_email_contactperson_email_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complianceinformation',
            old_name='auditor_license_number',
            new_name='license_number',
        ),
        migrations.RenameField(
            model_name='complianceinformation',
            old_name='tax_agent_ssm_number',
            new_name='ssm_number',
        ),
        migrations.RemoveField(
            model_name='complianceinformation',
            name='auditor_address',
        ),
        migrations.RemoveField(
            model_name='complianceinformation',
            name='tax_agent_address',
        ),
        migrations.AddField(
            model_name='complianceinformation',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complianceinformation',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='complianceinformation',
            name='address_line3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='complianceinformation',
            name='postcode',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator(message='Postcode must be exactly 5 digits.', regex='^\\d{5}$')]),
        ),
        migrations.AddField(
            model_name='complianceinformation',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='complianceinformation',
            name='town',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
