# Generated by Django 5.2.4 on 2025-08-02 14:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_rename_auditor_license_number_complianceinformation_license_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complianceinformation',
            name='aud_address_line1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complianceinformation',
            name='aud_address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='complianceinformation',
            name='aud_address_line3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='complianceinformation',
            name='aud_postcode',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator(message='Postcode must be exactly 5 digits.', regex='^\\d{5}$')]),
        ),
        migrations.AddField(
            model_name='complianceinformation',
            name='aud_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='complianceinformation',
            name='aud_town',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
