# Generated by Django 5.2.4 on 2025-08-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_complianceinformation_aud_address_line1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='is_contact_person',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shareholder',
            name='is_contact_person',
            field=models.BooleanField(default=False),
        ),
    ]
