# Generated by Django 5.2.4 on 2025-08-05 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_director_is_contact_person_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactperson',
            old_name='email_address',
            new_name='email',
        ),
    ]
