# Generated by Django 5.2.4 on 2025-08-08 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_rename_email_address_contactperson_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactperson',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contactperson', to='companies.company'),
        ),
    ]
