# Generated by Django 5.2.4 on 2025-08-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0015_alter_contactperson_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ssm_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
