# Generated by Django 5.2.4 on 2025-08-11 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0016_alter_company_ssm_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="A friendly name for this template (e.g. 'Director Appointment Letter')", max_length=255)),
                ('file', models.FileField(help_text='Upload a .docx template file', upload_to='doc_templates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
