# Generated by Django 5.2.4 on 2025-08-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0017_documenttemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttemplate',
            name='file',
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='github_url',
            field=models.URLField(default='https://example.com'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
