# Generated by Django 5.2.4 on 2025-08-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0018_remove_documenttemplate_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='per_director',
            field=models.BooleanField(default=False, help_text='Generate one document per director when checked'),
        ),
    ]
