# Generated by Django 5.2.4 on 2025-08-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0019_documenttemplate_per_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='category',
            field=models.CharField(choices=[('resolutions', 'Resolutions'), ('letters', 'Letters'), ('forms', 'Forms'), ('misc', 'Miscellaneous')], default='misc', max_length=50),
        ),
    ]
